### ISSUE TITLE
Add images to your readme?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [hammy3502/scrcpy-gui#6]
I've noticed that projects that have images in their readme file get a lot more attention than those with just text.  

Your program is a visual one.  People are curious what it looks like.  Even what you believe is the most basic looking GUI is often interesting to other people.

**Comment by hammy275** [comment]
Thanks for the idea! They've been added in commit [9c6c59e](https://github.com/hammy3502/scrcpy-gui/commit/9c6c59ed35c14d0bb7368f7daedbd6807af111a1).
